controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    acker_cont:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

acker_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link
    # odom_frame_id: odom

    rear_wheels_names: [rear_right_wheel_joint, rear_left_wheel_joint]
    front_wheels_names: [front_right_steering_joint, front_left_steering_joint]
    wheelbase: 0.6
    front_wheel_track: 0.42
    rear_wheel_track: 0.42
    front_wheels_radius: 0.1
    rear_wheels_radius: 0.1 
    max_steering_angle: 0.3927  # π/8 radians = 22.5 degrees
    min_steering_angle: -0.3927 # -π/8 radians = -22.5 degrees
    
    use_stamped_vel: false
    # enable_odom_tf: true 



# joint_broad:
#   ros__parameters: